config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :comments
  end
  get '/dashboard' => 'dashboard#index', as: :user_root
  get '/comments/:id', to: 'comments#show', as: 'comment'
  resources :users, only: [:show]
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true

  delegate :username, to: :user
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :title, presence: true
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_writer :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  validates_length_of :username, minimum: 5, maximum: 25
  validate :validate_username

  def username
    return self.email.split('@').first
  end

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
    #@comments = @book.comments.where(allow: true)
    redirect_to :controller => 'dashboard', :action => 'index'
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :pagecount, :share)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.allow = false
    @comment.save
    redirect_to user_path(User.find(@book.user_id))
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
    @comment.allow = true
    @comment.save
    redirect_to book_path(Book.find(@comment.book_id))
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = current_user.books
    @comments = Comment.where(book_id: @books.each {|book| book.id}, allow: false)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      @my_books = current_user.books
    end
    @books = Book.all.where(share: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :pagecount %>
    <%= form.number_field :pagecount %>
  </div>

  <div class="field">
    <%= form.label :share %>
    <%= form.check_box :share %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Pagecount</th>
      <th>Share</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.pagecount %></td>
        <td><%= book.share %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Pagecount:</strong>
  <%= @book.pagecount %>
</p>

<p>
  <strong>Share:</strong>
  <%= @book.share %>
</p>
<% if current_user == @book.user %>
  <td><%= link_to 'Edit', edit_book_path(@book) %></td>
  <td><%= link_to 'Delete', books_path,
                  data: { confirm: 'Are you sure?' } %></td>
<% end %>
<hr>
<h3> Comments</h3>
<% @comments.each do |comment| %>
  <p>
    <strong>Title:</strong>
    <%= comment.title %>
  </p>
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>
<% end %>
<hr>

<h3>Add Comments</h3>
<%= form_with(model: [ @book, @book.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_field :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<hr>

app/views/comments/show.html.erb
<h1>Content</h1>
<h2><%= Book.find(@comment.book_id).title %> book comment</h2>
<h3>Title: <%= @comment.title %></h3>
<h3>Content: <%= @comment.content %></h3>
<%= link_to "Approve", edit_book_comment_path(@comment.id)%>

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dashboard</h1>
<h2>Books</h2>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Pagecount</th>
    <th>Share</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.pagecount %></td>
      <td><%= book.share %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

<h2>Comments</h2>

<% @comments.each do |comment| %>
  <tr>
    <td>
      <strong>
        <%= link_to "#{User.find(comment.user_id).username} wrote a comment your #{Book.find(comment.book_id).title} book. Clik here to accept it.", comment_path(comment) %>
      </strong>
    </td>
    <br>
  </tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
      <%= link_to "Dashboard", "/dashboard", :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Profile</h1>
<h3>Username: <%= @user.username %></h3>
<h3>Email: <%= @user.email %></h3>
<h3>Books</h3>
<% if @books.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
    </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h4>Henüz hiç kitap eklenmemiş.</h4>
<% end %>

app/views/welcome/index.html.erb
<h1>BooksShare</h1>

<h2>Books</h2>
<% if @books.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
    </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h3>Henüz hiç kitap eklenmemiş.</h3>
<% end %>